### ISSUE TITLE
Where did you find the register file for IP2368

### ISSUE THREAD

**Issue by jackzjh001** [InterfaceGUI/IP2368.h#2]
I look for the register file from nearly every entry searched on google or Baidu, the best I could find is the data sheet.
So would you please share the link of the register file, thank you!

**Comment by InterfaceGUI** [comment]
I found the complete document here: http://bbs.eeworld.com.cn/thread-1233736-1-1.html

**Comment by D-314** [comment]
Can you please share the register file by adding it to the repository or by attaching it in the reply to this comment?

**Comment by D-314** [comment]
[IP2368_I2C_COUT(with reg) V1.61 EN.pdf](https://github.com/InterfaceGUI/IP2368.h/files/14873947/IP2368_I2C_COUT.with.reg.V1.61.EN.pdf)
[IP2368_I2C_COUT(with reg) V1.61 CN.pdf](https://github.com/InterfaceGUI/IP2368.h/files/14873949/IP2368_I2C_COUT.with.reg.V1.61.CN.pdf)
